### ISSUE TITLE
Lambda variable capturing

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#10]
学C++手动声明还是自动检测？我觉得应该是后者，但是这件事应该经过商量。

**Comment by Seng-Jik** [comment]
我觉得也是自动检测

**Comment by ice1000** [comment]
Get

**Comment by ice1000** [comment]
那你觉得，是生成一个struct然后传入被捕获变量好，还是把被捕获变量挨个传入好？

**Comment by ice1000** [comment]
@SmallLuma

**Comment by Seng-Jik** [comment]
挨个传入吧。
生成一个struct感觉要多写很多。
或者我们可以用元组，不过目前还没有定这个语法。

**Comment by ice1000** [comment]
元组不就是动态生成struct吗。。。

**Comment by ice1000** [comment]
clang的做法是生成了一个类来放。好处就是，在把capture了变量的lambda传递给其他函数时，这个生成的类也要跟着一起被传递出去。那么如果只有一个类，那增加的参数也就只有一个。挨个传入的话就是动态确定的。

我现在也拿不定主意，其实。

**Comment by Seng-Jik** [comment]
不过我觉得还是自动检测比较好

**Comment by ice1000** [comment]
我都没反对了，肯定自动检测啊。

感觉西佳佳的做法挺好的，我就参考西佳佳了
