### ISSUE TITLE
about traits and interfaces

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#17]
我觉得我们应该引入不支持继承的接口（或者叫trait，名字不一样而已），然后使用合成类型来代替继承。很妙。按理说。

但是也有很多严重的问题，比如这肯定涉及类似虚函数表的东西。我觉得我们可以在编译后把这个搞成模板。你们怎么看？

**Comment by ice1000** [comment]
不行，我觉得模板有几分猥琐，但是虚函数表有性能问题。

**Comment by ice1000** [comment]
就是多态。

**Comment by Seng-Jik** [comment]
动态绑定肯定是少不了的吧
最正常的实现interface的方法大概就是动态绑定了

**Comment by Seng-Jik** [comment]
另外我们可以用struct来代替trait

**Comment by SmallLuma** [comment]
打错，trait

**Comment by ice1000** [comment]
咋代替？Struct不是放数据的吗

**Comment by ice1000** [comment]
动态绑定咋做啊，说个思路啊，我现在是懵的

**Comment by Seng-Jik** [comment]
哦，想错了，直接用结构体存储函数就是。
然后用带有函数的结构体和带有数据的结构体组合成类，只允许一个结构体public，其余结构体均为private

**Comment by ice1000** [comment]
我觉得你这不科学，说好的一切皆扩展函数+结构体呢

**Comment by ice1000** [comment]
要是有了模板，就可以鄙视Go了

**Comment by ice1000** [comment]
Superseded by #20
