### ISSUE TITLE
About macros

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#18]
要不要考虑加入宏来实现一定程度的代码复用？

而且C风格宏和Rust风格宏，实现难度不一样，做出来后用起来爽的程度也不一样。我不是很清楚，看你们的想法。（表达式拆分做起来蛋疼啊）

**Comment by Seng-Jik** [comment]
那不如用模板

**Comment by ice1000** [comment]
但是模板也不一定做得出来。要是我们不OO，也就是说没有接口和继承，那模板和泛型就等价了。宏的话我觉得主要是可以和现在这个后端分开处理，我现在暂时就不用为了这个而重构。

**Comment by Seng-Jik** [comment]
但是这样宏会比较脏啊，除非能把宏搞进名称空间

**Comment by ice1000** [comment]
我说的是高级宏，当然是卫生的(

**Comment by ice1000** [comment]
另外：如果做模板的话，估计没法编译模板，只能像C++一样弄成编译期的，而且只能把类型替换进去

**Comment by ice1000** [comment]
弃用此方案。
