### ISSUE TITLE
What exactly is "string"?

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#19]
我们的字符串字面量应该是转化成`string`这个类型的，但是这个类型到底是什么？它是否应该是高度封装的？还是就是一个`vec<i8>`的别名？

Java中，字符串是高度封装的，immutable。 C++中，字符串是（因为傻逼C）`char*`，而且辣鸡clang还合并常量，性质极其恶劣。

你们如何评价？如何看待？要不要char这个类型？或者干脆和i8当成一个东西？

以及，要不要提供多种不同的字符串字面量？比如，`"boy next door"c` 变成`vec<i8>`，`"boy next door"`变成`string`。

**Comment by ice1000** [comment]
如果要说根据应用场合而定，这种用于图形学和底层编程的语言到底需要的是啥？

我觉得很有必要提供多种字面量，不然就会变得和Rust的字符串一样感觉很。。。很乱。（也有可能是我智商原因搞不清楚）

**Comment by Seng-Jik** [comment]
string已经是基本类型了吧

**Comment by ice1000** [comment]
那暴露内部实现吗？你觉得封装里面的char数组好还是不封装

**Comment by AkimotoAkari** [comment]
啥- -string就一个数组就好啦
各种黑魔法什么的，还是用库实现吧- -

**Comment by ice1000** [comment]
Java的string就是高度封装的，起码做到了immutable。如果是搞成恰数组的话，黑魔法写库里那也只能当成C语言的string.h用，不知道会不会略显贫瘠

**Comment by nobodxbodon** [comment]
> 如果要说根据应用场合而定，这种用于图形学和底层编程的语言到底需要的是啥？

从需求出发+1. 请问和C/C++的应用领域有什么不同呢?
感觉封装和性能有点鱼和熊掌.

**Comment by ice1000** [comment]
封装和性能是可以兼得的，只要编译器牛逼。你看Rust，模式匹配、trait、合成类型、闭包、各种Monad，哪一个不是层次极高的抽象？性能依旧可以和C++比肩。 :trollface:

我们的目标也是这个。从大规模内联做起，我们的目标是~~没有蛀牙~~把能内联的lambda都内联，因此高度抽象的函数式风格代码能运行的和imperative的差不多快，然后比如把if while啥的尽可能去掉，这样可以在gpu上跑的最快。

和C++的区别是，这门语言用了另一种抽象的思路(结构体加扩展函数肛爆OOP)，然后没有历史包袱。而且这门语言是为熟练的程序员设计的，有一些萌新可能不理解的东西。比如，我把所有lambda自动的加上了yc，用recur就能找到指向自己的指针。

**Comment by ice1000** [comment]
@nobodxboden

**Comment by ice1000** [comment]
@nobodxbodon

**Comment by nobodxbodon** [comment]
Rust的速度看起来不错, 不过耗内存好像[明显大一些](http://benchmarksgame.alioth.debian.org/u64q/rust.html). 那么打算做哪些超越Rust的功能呢?
GPU编译优化的水好像蛮深的. 另外Rust好像也有讨论如何支持OpenCL.

**Comment by ice1000** [comment]
我不是[说了吗](https://github.com/Cm-lang/Cm-Document/issues/19#issuecomment-327430593)

**Comment by Seng-Jik** [comment]
回复：那暴露内部实现吗？你觉得封装里面的char数组好还是不封装

string不暴露内部实现，但是提供.ToArray()这样的方法。

**Comment by ice1000** [comment]
我日啊，现在我发现这些数组和指针的隐式转换是真的坑，你代码可以把数组扔给指针但是llvm只认完全一样的类型，必须`load`而且我都不知道load是干啥的
:sob: 好气啊
