### ISSUE TITLE
Do we really need object-oriented features?

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#20]
根据我在群里的说法，我们现在想到的各种non-OO的特性已经可以基本上代替OO了。

实际上，完全去掉class的概念，保留struct、扩展函数、操作符重载、lambda变量重载，基本上就很牛批了。 :trollface:

**Comment by ice1000** [comment]
哦还有模板

**Comment by Seng-Jik** [comment]
但是还是得有访问权控制的问题

**Comment by ice1000** [comment]
咋控制？同一个文件public然后对外可选？

**Comment by ice1000** [comment]
https://github.com/Cm-lang/Cm-Document/issues/20#issuecomment-327157011

我就姑且理解为你同意扔掉OO了。

**Comment by ice1000** [comment]
OK! Fuck OO.
