### ISSUE TITLE
About digit literals

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#22]
@SmallLuma 我要求Parser在解析的时候把二进制和16进制处理了，分别使用0b和0x作为前缀。

0o作为8进制，后期再决定要不要。

**Comment by AkimotoAkari** [comment]
这个统一弄成int就好？然后根据大小/参数决定长度就好

**Comment by ice1000** [comment]
不是。。Int目前决定做成Rust那样

**Comment by ice1000** [comment]
逼翼在群里说0o好，别的也可以。那就关了
