### ISSUE TITLE
About operators

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#23]
两种想法：

0. 随便你怎么定义二元运算符，反正当成函数（Haskell
1. 像C++/Kotlin那样钦点几个，然后特殊处理

如果是前者，是否要允许自定义优先级和结合性（Haskell支持

如果是后者，有哪些钦点。我目前想的是：

```ruby
+ - * % ^ & | $ ! !! ? () / += -= *= /= |= &= < > >= <= <=> <+> <*> <> <|> <$> >>= =<< >>> <<< || && \\
```

**Comment by Seng-Jik** [comment]
肯定选0啊，然后大概可以这样声明？

```Cm
func operator TypeA + TypeB : TypeC { /***/ }  //二元
func operator ++TypeA : TypeA { /***/ }   //一元
```

结构体里的写法尚未想好

**Comment by ice1000** [comment]
另，我觉得whitespaces and keywords可以merge掉了，因为这个规则是没啥好商量的，而且关键词以后加减那都只是一行一行地改，我觉得没啥影响。

**Comment by ice1000** [comment]
声明的时候也需要声明左右两个变量的类型和函数名，毕竟这些都是函数
