### ISSUE TITLE
Notepad++ syntax highlight

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#24]
帅不帅

![image](https://user-images.githubusercontent.com/16398479/30120006-312b2458-935a-11e7-9dd7-c6aace2db9ec.png)

放在 https://github.com/ice1000/NppExtension 里的

**Comment by Seng-Jik** [comment]
这个很好啊

**Comment by AkimotoAkari** [comment]
Hey dear developers,
I'm going to develop things in Cm but i'm now working on VS Code.
Is there any solutions to syntax highlighting in VS Code?
(BTW, stackexchange is really awesome!

**Comment by ice1000** [comment]
Coming soon

**Comment by AkimotoAkari** [comment]
Ah, many thanks:)
