### ISSUE TITLE
Allow non-lambda overloading

### ISSUE THREAD

**Issue by thautwarm** [bC-Programming-Language-StandardCouncil/bC-Document#26]
比如Lambda与Primary之间是否可以重载。  
```rust
func foo : void
{ f : i32() -> f(); }

var foo:i32 = 1;
```  
以上代码是否合法？

**Comment by ice1000** [comment]
实现是很简单的。就看是否清真的问题。

**Comment by ice1000** [comment]
另：同时存在重载的lambda和值时会很坑，必须要确定一个。否则就很恼火，很糟心。

**Comment by ice1000** [comment]
`Environment.Find*`

就是用来做Resolve的，快去看

**Comment by thautwarm** [comment]
我翻译到这里的时候再来问大家的想法，Py那边要支持这个没有啥问题。  
现在我并不是很确定这种重载是否合理。。。

**Comment by ice1000** [comment]
@SmallLuma

**Comment by ice1000** [comment]
我今天在梦呓时发现了这个问题的不合理性。因为很多时候，lambda会惨遭内联或者被退化成一个函数，而函数是全局的，因此同一个名字对应多个lambda是没有问题的。

但变量就不一样。举个例子，delete操作是仅根据变量名查找指针的，而同一作用域下的多个重载的变量在同时需要delete时，就只能delete最后一个。这是这个方案的傻逼之处。

想到了一个解决方案：delete with type。

```cpp
let a = new A()
let a = new B()
delete a: A
```
