### ISSUE TITLE
About LiteralExpression

### ISSUE THREAD

**Issue by thautwarm** [bC-Programming-Language-StandardCouncil/bC-Document#27]
[AST](https://github.com/Cm-lang/Cmc/blob/master/Cmc/Cm_AST_Design.yml)
没有DoubleLiteralExpression和FloatLiteralExpression，这个东西是打算怎么做？

**Comment by ice1000** [comment]
你加一个吧，这两个应该是同一个类，你模仿IntLiteral那个写一个就是了，然后Environment里面的预置类型加上f32 f64这些

**Comment by ice1000** [comment]
Added.
