### ISSUE TITLE
For-each syntax sugar

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#29]
请求加入

For-each语法糖
For comprehension/do notation语法糖
类似C# Linq的语法糖

这些东西Parse的时候就处理掉。或者我整个desugar的util

**Comment by Seng-Jik** [comment]
使用C++的for( : )语法吧
Parse的时候处理不掉，因为目前没搞好迭代器，也没有类似length这样的操作。

**Comment by ice1000** [comment]
哦，那for comprehension呢
即

```kotlin
a.flatMap { b ->
  b.flatMap { c ->
    c.flatMap { d -> f(d) }
  }
}
```
简写为
```scala
for(
  b <- a
  c <- b
  d <- c) yield f(d)
```

**Comment by ice1000** [comment]
好的。For-each应该这样：先看是不是数组或者列表或者range啥的，如果是就朴素循环，否则用迭代器，是吧

然后for comprehension应该可以parse的时候处理，因为是钦定，硬点的

**Comment by Seng-Jik** [comment]
全部使用迭代器吧，数组也可以建立迭代器就是

**Comment by ice1000** [comment]
但是我心理上觉得迭代器比较慢诶 :trollface: (

**Comment by ice1000** [comment]
诶但如果照你这么说，for each是可以在parse的时候desugar的。。。 :trollface:

**Comment by lfkdsk** [comment]
@ice1000 迭代器最好能有隐式的 index 提供，而且可以尝试给 AST 增加预处理环节？

**Comment by ice1000** [comment]
@lfkdsk 可能举个例子比较容易能表达你的想法。在使用迭代器的时候隐式提供index并不容易啊

**Comment by ice1000** [comment]
还是去掉好了，因为有forEach这类高阶函数
