### ISSUE TITLE
String type

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#3]
I need a string type while developing the compiler. Currently, it's `string`.

Possible alternatives:

+ `String`
+ `vec<u8>`

**Comment by Seng-Jik** [comment]
"string" is a first class type.

example:

x = "hello";
x : string = "hello";
x : string^ = "hello";
x : string[] = {"hello","hello"};
x : string^[] = {"hello","hello"};

**Comment by ice1000** [comment]
OK
