### ISSUE TITLE
About modules

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#33]
如何设计 module 这一概念？

**Comment by thautwarm** [comment]
静态语言我也不知道咋搞。  
用命名来分割？比如用户的每个下划线都会被变成两个下划线，而奇数下划线则用来分离作用域？

**Comment by AkimotoAkari** [comment]
或许弄成类似于命名空间之类的，然后弄个像Java 那样超级长的包名～总之不要像node那样就好了（可以预编译可以有自定build脚本那种就最好啦，所以还是想一下把它当成脚本那样运行的机制？

**Comment by ice1000** [comment]
很有道理

**Comment by ice1000** [comment]
我的想法：

文件开头可以有一句module声明，它的作用是把后面的所有变量的名字加上这个module前缀。避免歧义的方法就跟 @thautwarm 说的那样。然后import语句的作用(或者using(C#), use(Rust), require (Ruby, JS))就是给这些变量起“去掉了前缀的别名”。默认自动import自己的文件。

**Comment by ice1000** [comment]
感觉屌爆了(雾

**Comment by thautwarm** [comment]
close吧，我觉得ok
