### ISSUE TITLE
Supporting overloading

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#4]
lambda类型的变量需要这样：

```bc
val lambda: func i8(int) = xxx
val lambda: func i8(string) = xxx
lambda(233) // 会resolve为上面那个
```

以此来支持重载。

而且只会在这种情况下这样处理：

+ 函数调用语句的函数名是直接给出的，不是什么东西的返回值

比如`lambda(xx)` 就是直接给出lambda这个名字，如果你是`findLambda(xxx)(xxx)`，就不这样，就认定那个返回的lambda（好像也只能这样）。

**Comment by ice1000** [comment]
@AkimotoAkari @SmallLuma

**Comment by ice1000** [comment]
同理，变量也能这样处理。我已经知道怎么写了。你们可以说说你们自己的看法。

**Comment by Seng-Jik** [comment]
参数的类型我觉得作为lambda函数签名的一部分比较好，这样也可以较好的支持lambda重载。
不过变量也这样处理具体是？

**Comment by ice1000** [comment]
就是

```kotlin
val a = 233
val a = "ass we can"
print(1+a) // 可以找到上面那个a
```

**Comment by ice1000** [comment]
> 参数的类型我觉得作为lambda函数签名的一部分

我就是这样整的啊

**Comment by AkimotoAkari** [comment]
常量重载不会弄得很麻烦么
顺带编译器可以给函数加后缀
例如说lambda@@1@i8@int
我需要语法（一脸懵逼

**Comment by Seng-Jik** [comment]
已写入草案，详见“变量与常量”中的“变量、常量重载”

**Comment by ice1000** [comment]
我知道，我差不多就是这个意思，只是后缀应该不能有\@，因为LLVM
